### ISSUE TITLE
Code is not "cool"

### ISSUE THREAD

**Issue by UnsignedByte** [Nichodon/cowbot#33]
# Expected Behavior
Cool features as stated in the **[description](https://github.com/Nichodon/cowbot)**

# Actual Behavior
Useless features, unoriginal features, and overall **not-cool** features.

# Steps to Reproduce
Use the bot and/or look at the code.

# Operating System
**MacBook Pro (Retina, 15-inch, Mid 2015)**
**Processor** 2.8 GHz Intel Core i7
**Memory** 16 GB 1600 MHz DDR3
**Graphics** AMD Radeon R9 M370X 2048 MB, Intel Iris Pro 1536 MB

**Comment by Nichodon** [comment]
Hi @UnsignedByte! Thanks for stopping by. Unfortunately, we do not support the OS you use as it is definitely not our priority to support degenerate systems. In order to fix this, you might have to purchase a better computer to see cowbot's "cool" features.

**Comment by UnsignedByte** [comment]
Hey @Nichodon! Thanks for replying. I think I sort of understand the problem now. Being on Windows must've impaired your sight capabilities, with its ugly UI. That would explain why you think "MacBook" equates to "Surface Book". This also explains the revolting overuse of **if** and **elif** statements in your code. Furthermore, your choice to use Windows would explain why you *think* your features are **cool**, but any sane human can see otherwise. Maybe you should try using Mac, or even better, **Chrome OS.**

**Comment by anematode** [comment]
Operating System

Nico's computer (Windows, 1984)
Processor 2.8 MHz Intel Core i69
Memory 1 MB 00 MHz DDR3
Graphics AMD Radeon R9 M370X 2048 MB, Intel Iris Pro 1536 MB
