### ISSUE TITLE
Repository owner is closing useful issues and not fixing the bot.

### ISSUE THREAD

**Issue by UnsignedByte** [Nichodon/cowbot#35]
# Expected Behavior
Repository owner has no programming skills but is willing to try to fix problems.

# Actual Behavior
Repository owner still has no programming skills, but ignores problems and won't fix them.

# Steps to Reproduce
Create an Issue on the bot

# Operating System
**MacBook Pro (Retina, 15-inch, Mid 2015)**
**Processor** 2.8 GHz Intel Core i7
**Memory** 16 GB 1600 MHz DDR3
**Graphics** AMD Radeon R9 M370X 2048 MB, Intel Iris Pro 1536 MB

**Comment by Nichodon** [comment]
Hi, @UnsignedByte! The reason #33 was closed was because there was a sudden influx of spam comments on that issue. I have re-opened the issue, hopefully that fixes.
